name: Sugestão de Melhoria
description: Sugestão de melhoria para a plataforma
title: "[MELHORIA] "
labels:
  - Sugestão de Melhoria

body:
  - type: dropdown
    id: product
    attributes:
      label: "Produto que será melhorado:"
      description: Em qual produto a melhoria foi identificada?
      options:
        - Afinando
        - Audiofoco
        - AudBility
        - Admin
        - Outros

    validations:
      required: true

  - type: textarea
    id: improvement_description
    attributes:
      label: "Detalhes da Melhoria:"
      value: |
        ## Descrição:

        ## Objetivo:

        ## Requisitos sugeridos:

        ## Benefícios esperados:


        ## Evidência

        [Cole ou arraste a imagem aqui]
    validations:
      required: true